openapi: 3.0.3
info:
  title: CV API
  description: CV API
  version: 1.0.0

servers:
  - url: 'https'

paths:
  "/attributes":
    get:
      summary: "属性情報群取得"
      description: "氏名や生年月日等の属性情報群を取得する。"
      tags: ["public"]
      deprecated: false
      responses:
        "200":
          description: "a"
