openapi: 3.0.3
info:
  title: CV API
  description: CV API
  version: 1.0.0
servers:
- url: "http://localhost:{port}/{version}"
  description: ローカル環境
  variables:
    port:
      description: ポート番号
      enum:
      - "8080"
      - "3000"
      default: "8080"
    version:
      description: APIバージョン
      enum:
      - v1
      default: v1
tags:
- name: users
  description: ユーザーに対するCRUD
paths:
  /users/{userId}/attributes:
    get:
      tags:
      - users
      summary: 属性情報群取得
      description: 氏名や生年月日等の属性情報群を取得する。
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/UserId'
        example: 9m4e2mr0ui3e8a215n4g
      responses:
        "200":
          description: 指定ユーザーの属性群を返却する。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAttribute'
        "404":
          description: 指定ユーザー自身、または、その属性群が存在しない。
      deprecated: false
components:
  schemas:
    UserId:
      maxLength: 20
      minLength: 20
      type: string
      description: ユーザーを一意に識別するID
      nullable: false
      example: 9m4e2mr0ui3e8a215n4g
      deprecated: false
    UserName:
      maxLength: 100
      minLength: 1
      type: string
      description: ユーザーの本名
      nullable: false
      example: 山田太郎
      deprecated: false
    UserNickName:
      maxLength: 100
      minLength: 0
      type: string
      description: ユーザーのニックネーム
      nullable: true
      example: ドカベン
      deprecated: false
    Url:
      maxLength: 4096
      minLength: 0
      type: string
      description: URL
      nullable: true
      example: https://www.gravatar.com/avatar/205e460b479e2e2248aec07710c08d50
      deprecated: false
    Year:
      maximum: 9999
      minimum: 1900
      type: integer
      description: 生年月日の「年」
      format: int32
      nullable: false
      example: 2022
      deprecated: false
    Month:
      maximum: 12
      minimum: 1
      type: integer
      description: 生年月日の「月」
      format: int32
      nullable: false
      example: 9
      deprecated: false
    Day:
      maximum: 31
      minimum: 1
      type: integer
      description: 生年月日の「日」
      format: int32
      nullable: false
      example: 10
      deprecated: false
    BirthDay:
      type: object
      properties:
        year:
          $ref: '#/components/schemas/Year'
        month:
          $ref: '#/components/schemas/Month'
        day:
          $ref: '#/components/schemas/Day'
      description: 生年月日
      nullable: false
      example: "{year: 2022, month: 9, day:10}"
      deprecated: false
    UserAttribute:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/UserName'
        nickname:
          $ref: '#/components/schemas/UserNickName'
        avatarUrl:
          $ref: '#/components/schemas/Url'
        birthday:
          $ref: '#/components/schemas/BirthDay'
      description: １ユーザーの属性情報群
      example:
        birthday: "{year: 2022, month: 9, day:10}"
        avatarUrl: https://www.gravatar.com/avatar/205e460b479e2e2248aec07710c08d50
        name: 山田太郎
        nickname: ドカベン
  parameters:
    userId:
      name: userId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/UserId'
      example: 9m4e2mr0ui3e8a215n4g
