// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky0621/cv-admin/src/ent/careerskill"
	"github.com/sky0621/cv-admin/src/ent/careerskillgroup"
	"github.com/sky0621/cv-admin/src/ent/usercareer"
)

// CareerSkillGroupCreate is the builder for creating a CareerSkillGroup entity.
type CareerSkillGroupCreate struct {
	config
	mutation *CareerSkillGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (csgc *CareerSkillGroupCreate) SetCreateTime(t time.Time) *CareerSkillGroupCreate {
	csgc.mutation.SetCreateTime(t)
	return csgc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (csgc *CareerSkillGroupCreate) SetNillableCreateTime(t *time.Time) *CareerSkillGroupCreate {
	if t != nil {
		csgc.SetCreateTime(*t)
	}
	return csgc
}

// SetUpdateTime sets the "update_time" field.
func (csgc *CareerSkillGroupCreate) SetUpdateTime(t time.Time) *CareerSkillGroupCreate {
	csgc.mutation.SetUpdateTime(t)
	return csgc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (csgc *CareerSkillGroupCreate) SetNillableUpdateTime(t *time.Time) *CareerSkillGroupCreate {
	if t != nil {
		csgc.SetUpdateTime(*t)
	}
	return csgc
}

// SetLabel sets the "label" field.
func (csgc *CareerSkillGroupCreate) SetLabel(s string) *CareerSkillGroupCreate {
	csgc.mutation.SetLabel(s)
	return csgc
}

// SetCareerID sets the "career" edge to the UserCareer entity by ID.
func (csgc *CareerSkillGroupCreate) SetCareerID(id int) *CareerSkillGroupCreate {
	csgc.mutation.SetCareerID(id)
	return csgc
}

// SetCareer sets the "career" edge to the UserCareer entity.
func (csgc *CareerSkillGroupCreate) SetCareer(u *UserCareer) *CareerSkillGroupCreate {
	return csgc.SetCareerID(u.ID)
}

// AddCareerSkillIDs adds the "careerSkills" edge to the CareerSkill entity by IDs.
func (csgc *CareerSkillGroupCreate) AddCareerSkillIDs(ids ...int) *CareerSkillGroupCreate {
	csgc.mutation.AddCareerSkillIDs(ids...)
	return csgc
}

// AddCareerSkills adds the "careerSkills" edges to the CareerSkill entity.
func (csgc *CareerSkillGroupCreate) AddCareerSkills(c ...*CareerSkill) *CareerSkillGroupCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return csgc.AddCareerSkillIDs(ids...)
}

// Mutation returns the CareerSkillGroupMutation object of the builder.
func (csgc *CareerSkillGroupCreate) Mutation() *CareerSkillGroupMutation {
	return csgc.mutation
}

// Save creates the CareerSkillGroup in the database.
func (csgc *CareerSkillGroupCreate) Save(ctx context.Context) (*CareerSkillGroup, error) {
	var (
		err  error
		node *CareerSkillGroup
	)
	csgc.defaults()
	if len(csgc.hooks) == 0 {
		if err = csgc.check(); err != nil {
			return nil, err
		}
		node, err = csgc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CareerSkillGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = csgc.check(); err != nil {
				return nil, err
			}
			csgc.mutation = mutation
			if node, err = csgc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(csgc.hooks) - 1; i >= 0; i-- {
			if csgc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = csgc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, csgc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CareerSkillGroup)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CareerSkillGroupMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (csgc *CareerSkillGroupCreate) SaveX(ctx context.Context) *CareerSkillGroup {
	v, err := csgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csgc *CareerSkillGroupCreate) Exec(ctx context.Context) error {
	_, err := csgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csgc *CareerSkillGroupCreate) ExecX(ctx context.Context) {
	if err := csgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csgc *CareerSkillGroupCreate) defaults() {
	if _, ok := csgc.mutation.CreateTime(); !ok {
		v := careerskillgroup.DefaultCreateTime()
		csgc.mutation.SetCreateTime(v)
	}
	if _, ok := csgc.mutation.UpdateTime(); !ok {
		v := careerskillgroup.DefaultUpdateTime()
		csgc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csgc *CareerSkillGroupCreate) check() error {
	if _, ok := csgc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "CareerSkillGroup.create_time"`)}
	}
	if _, ok := csgc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "CareerSkillGroup.update_time"`)}
	}
	if _, ok := csgc.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "CareerSkillGroup.label"`)}
	}
	if v, ok := csgc.mutation.Label(); ok {
		if err := careerskillgroup.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "CareerSkillGroup.label": %w`, err)}
		}
	}
	if _, ok := csgc.mutation.CareerID(); !ok {
		return &ValidationError{Name: "career", err: errors.New(`ent: missing required edge "CareerSkillGroup.career"`)}
	}
	return nil
}

func (csgc *CareerSkillGroupCreate) sqlSave(ctx context.Context) (*CareerSkillGroup, error) {
	_node, _spec := csgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (csgc *CareerSkillGroupCreate) createSpec() (*CareerSkillGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &CareerSkillGroup{config: csgc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: careerskillgroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: careerskillgroup.FieldID,
			},
		}
	)
	_spec.OnConflict = csgc.conflict
	if value, ok := csgc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: careerskillgroup.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := csgc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: careerskillgroup.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := csgc.mutation.Label(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: careerskillgroup.FieldLabel,
		})
		_node.Label = value
	}
	if nodes := csgc.mutation.CareerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   careerskillgroup.CareerTable,
			Columns: []string{careerskillgroup.CareerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: usercareer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.career_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := csgc.mutation.CareerSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   careerskillgroup.CareerSkillsTable,
			Columns: []string{careerskillgroup.CareerSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: careerskill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CareerSkillGroup.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CareerSkillGroupUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (csgc *CareerSkillGroupCreate) OnConflict(opts ...sql.ConflictOption) *CareerSkillGroupUpsertOne {
	csgc.conflict = opts
	return &CareerSkillGroupUpsertOne{
		create: csgc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csgc *CareerSkillGroupCreate) OnConflictColumns(columns ...string) *CareerSkillGroupUpsertOne {
	csgc.conflict = append(csgc.conflict, sql.ConflictColumns(columns...))
	return &CareerSkillGroupUpsertOne{
		create: csgc,
	}
}

type (
	// CareerSkillGroupUpsertOne is the builder for "upsert"-ing
	//  one CareerSkillGroup node.
	CareerSkillGroupUpsertOne struct {
		create *CareerSkillGroupCreate
	}

	// CareerSkillGroupUpsert is the "OnConflict" setter.
	CareerSkillGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateTime sets the "create_time" field.
func (u *CareerSkillGroupUpsert) SetCreateTime(v time.Time) *CareerSkillGroupUpsert {
	u.Set(careerskillgroup.FieldCreateTime, v)
	return u
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsert) UpdateCreateTime() *CareerSkillGroupUpsert {
	u.SetExcluded(careerskillgroup.FieldCreateTime)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *CareerSkillGroupUpsert) SetUpdateTime(v time.Time) *CareerSkillGroupUpsert {
	u.Set(careerskillgroup.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsert) UpdateUpdateTime() *CareerSkillGroupUpsert {
	u.SetExcluded(careerskillgroup.FieldUpdateTime)
	return u
}

// SetLabel sets the "label" field.
func (u *CareerSkillGroupUpsert) SetLabel(v string) *CareerSkillGroupUpsert {
	u.Set(careerskillgroup.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CareerSkillGroupUpsert) UpdateLabel() *CareerSkillGroupUpsert {
	u.SetExcluded(careerskillgroup.FieldLabel)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CareerSkillGroupUpsertOne) UpdateNewValues() *CareerSkillGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(careerskillgroup.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CareerSkillGroupUpsertOne) Ignore() *CareerSkillGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CareerSkillGroupUpsertOne) DoNothing() *CareerSkillGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CareerSkillGroupCreate.OnConflict
// documentation for more info.
func (u *CareerSkillGroupUpsertOne) Update(set func(*CareerSkillGroupUpsert)) *CareerSkillGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CareerSkillGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateTime sets the "create_time" field.
func (u *CareerSkillGroupUpsertOne) SetCreateTime(v time.Time) *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertOne) UpdateCreateTime() *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateCreateTime()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CareerSkillGroupUpsertOne) SetUpdateTime(v time.Time) *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertOne) UpdateUpdateTime() *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetLabel sets the "label" field.
func (u *CareerSkillGroupUpsertOne) SetLabel(v string) *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertOne) UpdateLabel() *CareerSkillGroupUpsertOne {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateLabel()
	})
}

// Exec executes the query.
func (u *CareerSkillGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CareerSkillGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CareerSkillGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CareerSkillGroupUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CareerSkillGroupUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CareerSkillGroupCreateBulk is the builder for creating many CareerSkillGroup entities in bulk.
type CareerSkillGroupCreateBulk struct {
	config
	builders []*CareerSkillGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the CareerSkillGroup entities in the database.
func (csgcb *CareerSkillGroupCreateBulk) Save(ctx context.Context) ([]*CareerSkillGroup, error) {
	specs := make([]*sqlgraph.CreateSpec, len(csgcb.builders))
	nodes := make([]*CareerSkillGroup, len(csgcb.builders))
	mutators := make([]Mutator, len(csgcb.builders))
	for i := range csgcb.builders {
		func(i int, root context.Context) {
			builder := csgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CareerSkillGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, csgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = csgcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, csgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, csgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (csgcb *CareerSkillGroupCreateBulk) SaveX(ctx context.Context) []*CareerSkillGroup {
	v, err := csgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csgcb *CareerSkillGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := csgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csgcb *CareerSkillGroupCreateBulk) ExecX(ctx context.Context) {
	if err := csgcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CareerSkillGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CareerSkillGroupUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (csgcb *CareerSkillGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *CareerSkillGroupUpsertBulk {
	csgcb.conflict = opts
	return &CareerSkillGroupUpsertBulk{
		create: csgcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (csgcb *CareerSkillGroupCreateBulk) OnConflictColumns(columns ...string) *CareerSkillGroupUpsertBulk {
	csgcb.conflict = append(csgcb.conflict, sql.ConflictColumns(columns...))
	return &CareerSkillGroupUpsertBulk{
		create: csgcb,
	}
}

// CareerSkillGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of CareerSkillGroup nodes.
type CareerSkillGroupUpsertBulk struct {
	create *CareerSkillGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CareerSkillGroupUpsertBulk) UpdateNewValues() *CareerSkillGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(careerskillgroup.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CareerSkillGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CareerSkillGroupUpsertBulk) Ignore() *CareerSkillGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CareerSkillGroupUpsertBulk) DoNothing() *CareerSkillGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CareerSkillGroupCreateBulk.OnConflict
// documentation for more info.
func (u *CareerSkillGroupUpsertBulk) Update(set func(*CareerSkillGroupUpsert)) *CareerSkillGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CareerSkillGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateTime sets the "create_time" field.
func (u *CareerSkillGroupUpsertBulk) SetCreateTime(v time.Time) *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertBulk) UpdateCreateTime() *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateCreateTime()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CareerSkillGroupUpsertBulk) SetUpdateTime(v time.Time) *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertBulk) UpdateUpdateTime() *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetLabel sets the "label" field.
func (u *CareerSkillGroupUpsertBulk) SetLabel(v string) *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CareerSkillGroupUpsertBulk) UpdateLabel() *CareerSkillGroupUpsertBulk {
	return u.Update(func(s *CareerSkillGroupUpsert) {
		s.UpdateLabel()
	})
}

// Exec executes the query.
func (u *CareerSkillGroupUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CareerSkillGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CareerSkillGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CareerSkillGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
