// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sky0621/cv-admin/src/ent/careertask"
	"github.com/sky0621/cv-admin/src/ent/careertaskdescription"
	"github.com/sky0621/cv-admin/src/ent/predicate"
)

// CareerTaskDescriptionQuery is the builder for querying CareerTaskDescription entities.
type CareerTaskDescriptionQuery struct {
	config
	ctx            *QueryContext
	order          []careertaskdescription.OrderOption
	inters         []Interceptor
	predicates     []predicate.CareerTaskDescription
	withCareerTask *CareerTaskQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CareerTaskDescriptionQuery builder.
func (ctdq *CareerTaskDescriptionQuery) Where(ps ...predicate.CareerTaskDescription) *CareerTaskDescriptionQuery {
	ctdq.predicates = append(ctdq.predicates, ps...)
	return ctdq
}

// Limit the number of records to be returned by this query.
func (ctdq *CareerTaskDescriptionQuery) Limit(limit int) *CareerTaskDescriptionQuery {
	ctdq.ctx.Limit = &limit
	return ctdq
}

// Offset to start from.
func (ctdq *CareerTaskDescriptionQuery) Offset(offset int) *CareerTaskDescriptionQuery {
	ctdq.ctx.Offset = &offset
	return ctdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctdq *CareerTaskDescriptionQuery) Unique(unique bool) *CareerTaskDescriptionQuery {
	ctdq.ctx.Unique = &unique
	return ctdq
}

// Order specifies how the records should be ordered.
func (ctdq *CareerTaskDescriptionQuery) Order(o ...careertaskdescription.OrderOption) *CareerTaskDescriptionQuery {
	ctdq.order = append(ctdq.order, o...)
	return ctdq
}

// QueryCareerTask chains the current query on the "careerTask" edge.
func (ctdq *CareerTaskDescriptionQuery) QueryCareerTask() *CareerTaskQuery {
	query := (&CareerTaskClient{config: ctdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(careertaskdescription.Table, careertaskdescription.FieldID, selector),
			sqlgraph.To(careertask.Table, careertask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, careertaskdescription.CareerTaskTable, careertaskdescription.CareerTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CareerTaskDescription entity from the query.
// Returns a *NotFoundError when no CareerTaskDescription was found.
func (ctdq *CareerTaskDescriptionQuery) First(ctx context.Context) (*CareerTaskDescription, error) {
	nodes, err := ctdq.Limit(1).All(setContextOp(ctx, ctdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{careertaskdescription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) FirstX(ctx context.Context) *CareerTaskDescription {
	node, err := ctdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CareerTaskDescription ID from the query.
// Returns a *NotFoundError when no CareerTaskDescription ID was found.
func (ctdq *CareerTaskDescriptionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctdq.Limit(1).IDs(setContextOp(ctx, ctdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{careertaskdescription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) FirstIDX(ctx context.Context) int {
	id, err := ctdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CareerTaskDescription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CareerTaskDescription entity is found.
// Returns a *NotFoundError when no CareerTaskDescription entities are found.
func (ctdq *CareerTaskDescriptionQuery) Only(ctx context.Context) (*CareerTaskDescription, error) {
	nodes, err := ctdq.Limit(2).All(setContextOp(ctx, ctdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{careertaskdescription.Label}
	default:
		return nil, &NotSingularError{careertaskdescription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) OnlyX(ctx context.Context) *CareerTaskDescription {
	node, err := ctdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CareerTaskDescription ID in the query.
// Returns a *NotSingularError when more than one CareerTaskDescription ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctdq *CareerTaskDescriptionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctdq.Limit(2).IDs(setContextOp(ctx, ctdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{careertaskdescription.Label}
	default:
		err = &NotSingularError{careertaskdescription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ctdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CareerTaskDescriptions.
func (ctdq *CareerTaskDescriptionQuery) All(ctx context.Context) ([]*CareerTaskDescription, error) {
	ctx = setContextOp(ctx, ctdq.ctx, "All")
	if err := ctdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CareerTaskDescription, *CareerTaskDescriptionQuery]()
	return withInterceptors[[]*CareerTaskDescription](ctx, ctdq, qr, ctdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) AllX(ctx context.Context) []*CareerTaskDescription {
	nodes, err := ctdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CareerTaskDescription IDs.
func (ctdq *CareerTaskDescriptionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ctdq.ctx.Unique == nil && ctdq.path != nil {
		ctdq.Unique(true)
	}
	ctx = setContextOp(ctx, ctdq.ctx, "IDs")
	if err = ctdq.Select(careertaskdescription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) IDsX(ctx context.Context) []int {
	ids, err := ctdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctdq *CareerTaskDescriptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ctdq.ctx, "Count")
	if err := ctdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ctdq, querierCount[*CareerTaskDescriptionQuery](), ctdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) CountX(ctx context.Context) int {
	count, err := ctdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctdq *CareerTaskDescriptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ctdq.ctx, "Exist")
	switch _, err := ctdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ctdq *CareerTaskDescriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := ctdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CareerTaskDescriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctdq *CareerTaskDescriptionQuery) Clone() *CareerTaskDescriptionQuery {
	if ctdq == nil {
		return nil
	}
	return &CareerTaskDescriptionQuery{
		config:         ctdq.config,
		ctx:            ctdq.ctx.Clone(),
		order:          append([]careertaskdescription.OrderOption{}, ctdq.order...),
		inters:         append([]Interceptor{}, ctdq.inters...),
		predicates:     append([]predicate.CareerTaskDescription{}, ctdq.predicates...),
		withCareerTask: ctdq.withCareerTask.Clone(),
		// clone intermediate query.
		sql:  ctdq.sql.Clone(),
		path: ctdq.path,
	}
}

// WithCareerTask tells the query-builder to eager-load the nodes that are connected to
// the "careerTask" edge. The optional arguments are used to configure the query builder of the edge.
func (ctdq *CareerTaskDescriptionQuery) WithCareerTask(opts ...func(*CareerTaskQuery)) *CareerTaskDescriptionQuery {
	query := (&CareerTaskClient{config: ctdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ctdq.withCareerTask = query
	return ctdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CareerTaskDescription.Query().
//		GroupBy(careertaskdescription.FieldDescription).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ctdq *CareerTaskDescriptionQuery) GroupBy(field string, fields ...string) *CareerTaskDescriptionGroupBy {
	ctdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CareerTaskDescriptionGroupBy{build: ctdq}
	grbuild.flds = &ctdq.ctx.Fields
	grbuild.label = careertaskdescription.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//	}
//
//	client.CareerTaskDescription.Query().
//		Select(careertaskdescription.FieldDescription).
//		Scan(ctx, &v)
func (ctdq *CareerTaskDescriptionQuery) Select(fields ...string) *CareerTaskDescriptionSelect {
	ctdq.ctx.Fields = append(ctdq.ctx.Fields, fields...)
	sbuild := &CareerTaskDescriptionSelect{CareerTaskDescriptionQuery: ctdq}
	sbuild.label = careertaskdescription.Label
	sbuild.flds, sbuild.scan = &ctdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CareerTaskDescriptionSelect configured with the given aggregations.
func (ctdq *CareerTaskDescriptionQuery) Aggregate(fns ...AggregateFunc) *CareerTaskDescriptionSelect {
	return ctdq.Select().Aggregate(fns...)
}

func (ctdq *CareerTaskDescriptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ctdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ctdq); err != nil {
				return err
			}
		}
	}
	for _, f := range ctdq.ctx.Fields {
		if !careertaskdescription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctdq.path != nil {
		prev, err := ctdq.path(ctx)
		if err != nil {
			return err
		}
		ctdq.sql = prev
	}
	return nil
}

func (ctdq *CareerTaskDescriptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CareerTaskDescription, error) {
	var (
		nodes       = []*CareerTaskDescription{}
		withFKs     = ctdq.withFKs
		_spec       = ctdq.querySpec()
		loadedTypes = [1]bool{
			ctdq.withCareerTask != nil,
		}
	)
	if ctdq.withCareerTask != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, careertaskdescription.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CareerTaskDescription).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CareerTaskDescription{config: ctdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ctdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ctdq.withCareerTask; query != nil {
		if err := ctdq.loadCareerTask(ctx, query, nodes, nil,
			func(n *CareerTaskDescription, e *CareerTask) { n.Edges.CareerTask = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ctdq *CareerTaskDescriptionQuery) loadCareerTask(ctx context.Context, query *CareerTaskQuery, nodes []*CareerTaskDescription, init func(*CareerTaskDescription), assign func(*CareerTaskDescription, *CareerTask)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CareerTaskDescription)
	for i := range nodes {
		if nodes[i].career_task_id == nil {
			continue
		}
		fk := *nodes[i].career_task_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(careertask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "career_task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ctdq *CareerTaskDescriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctdq.querySpec()
	_spec.Node.Columns = ctdq.ctx.Fields
	if len(ctdq.ctx.Fields) > 0 {
		_spec.Unique = ctdq.ctx.Unique != nil && *ctdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ctdq.driver, _spec)
}

func (ctdq *CareerTaskDescriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(careertaskdescription.Table, careertaskdescription.Columns, sqlgraph.NewFieldSpec(careertaskdescription.FieldID, field.TypeInt))
	_spec.From = ctdq.sql
	if unique := ctdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ctdq.path != nil {
		_spec.Unique = true
	}
	if fields := ctdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, careertaskdescription.FieldID)
		for i := range fields {
			if fields[i] != careertaskdescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctdq *CareerTaskDescriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctdq.driver.Dialect())
	t1 := builder.Table(careertaskdescription.Table)
	columns := ctdq.ctx.Fields
	if len(columns) == 0 {
		columns = careertaskdescription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctdq.sql != nil {
		selector = ctdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctdq.ctx.Unique != nil && *ctdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ctdq.predicates {
		p(selector)
	}
	for _, p := range ctdq.order {
		p(selector)
	}
	if offset := ctdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CareerTaskDescriptionGroupBy is the group-by builder for CareerTaskDescription entities.
type CareerTaskDescriptionGroupBy struct {
	selector
	build *CareerTaskDescriptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctdgb *CareerTaskDescriptionGroupBy) Aggregate(fns ...AggregateFunc) *CareerTaskDescriptionGroupBy {
	ctdgb.fns = append(ctdgb.fns, fns...)
	return ctdgb
}

// Scan applies the selector query and scans the result into the given value.
func (ctdgb *CareerTaskDescriptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctdgb.build.ctx, "GroupBy")
	if err := ctdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CareerTaskDescriptionQuery, *CareerTaskDescriptionGroupBy](ctx, ctdgb.build, ctdgb, ctdgb.build.inters, v)
}

func (ctdgb *CareerTaskDescriptionGroupBy) sqlScan(ctx context.Context, root *CareerTaskDescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ctdgb.fns))
	for _, fn := range ctdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ctdgb.flds)+len(ctdgb.fns))
		for _, f := range *ctdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ctdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CareerTaskDescriptionSelect is the builder for selecting fields of CareerTaskDescription entities.
type CareerTaskDescriptionSelect struct {
	*CareerTaskDescriptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ctds *CareerTaskDescriptionSelect) Aggregate(fns ...AggregateFunc) *CareerTaskDescriptionSelect {
	ctds.fns = append(ctds.fns, fns...)
	return ctds
}

// Scan applies the selector query and scans the result into the given value.
func (ctds *CareerTaskDescriptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctds.ctx, "Select")
	if err := ctds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CareerTaskDescriptionQuery, *CareerTaskDescriptionSelect](ctx, ctds.CareerTaskDescriptionQuery, ctds, ctds.inters, v)
}

func (ctds *CareerTaskDescriptionSelect) sqlScan(ctx context.Context, root *CareerTaskDescriptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ctds.fns))
	for _, fn := range ctds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ctds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
