// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sky0621/cv-admin/src/ent/skilltag"
)

// SkillTag is the model entity for the SkillTag schema.
type SkillTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SkillTagQuery when eager-loading is set.
	Edges        SkillTagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SkillTagEdges holds the relations/edges for other nodes in the graph.
type SkillTagEdges struct {
	// Skills holds the value of the skills edge.
	Skills []*Skill `json:"skills,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SkillsOrErr returns the Skills value or an error if the edge
// was not loaded in eager-loading.
func (e SkillTagEdges) SkillsOrErr() ([]*Skill, error) {
	if e.loadedTypes[0] {
		return e.Skills, nil
	}
	return nil, &NotLoadedError{edge: "skills"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SkillTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skilltag.FieldID:
			values[i] = new(sql.NullInt64)
		case skilltag.FieldName, skilltag.FieldKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SkillTag fields.
func (st *SkillTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skilltag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			st.ID = int(value.Int64)
		case skilltag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				st.Name = value.String
			}
		case skilltag.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				st.Key = value.String
			}
		default:
			st.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SkillTag.
// This includes values selected through modifiers, order, etc.
func (st *SkillTag) Value(name string) (ent.Value, error) {
	return st.selectValues.Get(name)
}

// QuerySkills queries the "skills" edge of the SkillTag entity.
func (st *SkillTag) QuerySkills() *SkillQuery {
	return NewSkillTagClient(st.config).QuerySkills(st)
}

// Update returns a builder for updating this SkillTag.
// Note that you need to call SkillTag.Unwrap() before calling this method if this SkillTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (st *SkillTag) Update() *SkillTagUpdateOne {
	return NewSkillTagClient(st.config).UpdateOne(st)
}

// Unwrap unwraps the SkillTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (st *SkillTag) Unwrap() *SkillTag {
	_tx, ok := st.config.driver.(*txDriver)
	if !ok {
		panic("ent: SkillTag is not a transactional entity")
	}
	st.config.driver = _tx.drv
	return st
}

// String implements the fmt.Stringer.
func (st *SkillTag) String() string {
	var builder strings.Builder
	builder.WriteString("SkillTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", st.ID))
	builder.WriteString("name=")
	builder.WriteString(st.Name)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(st.Key)
	builder.WriteByte(')')
	return builder.String()
}

// SkillTags is a parsable slice of SkillTag.
type SkillTags []*SkillTag
