// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sky0621/cv-admin/src/ent/usercareer"
)

// UserCareer is the model entity for the UserCareer schema.
type UserCareer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCareer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercareer.FieldID:
			values[i] = new(sql.NullInt64)
		case usercareer.FieldCreateTime, usercareer.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserCareer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCareer fields.
func (uc *UserCareer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercareer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uc.ID = int(value.Int64)
		case usercareer.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				uc.CreateTime = value.Time
			}
		case usercareer.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				uc.UpdateTime = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this UserCareer.
// Note that you need to call UserCareer.Unwrap() before calling this method if this UserCareer
// was returned from a transaction, and the transaction was committed or rolled back.
func (uc *UserCareer) Update() *UserCareerUpdateOne {
	return (&UserCareerClient{config: uc.config}).UpdateOne(uc)
}

// Unwrap unwraps the UserCareer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uc *UserCareer) Unwrap() *UserCareer {
	_tx, ok := uc.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCareer is not a transactional entity")
	}
	uc.config.driver = _tx.drv
	return uc
}

// String implements the fmt.Stringer.
func (uc *UserCareer) String() string {
	var builder strings.Builder
	builder.WriteString("UserCareer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", uc.ID))
	builder.WriteString("create_time=")
	builder.WriteString(uc.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(uc.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCareers is a parsable slice of UserCareer.
type UserCareers []*UserCareer

func (uc UserCareers) config(cfg config) {
	for _i := range uc {
		uc[_i].config = cfg
	}
}
